### ISSUE TITLE
Does this measure on what the window is focused. .. ?

### ISSUE THREAD

**Issue by Furshia** [christiankyle-ching/DigitalWellbeingForWindows#13]
Hello, this is a nice hobby project :) and was wondering if the focused window is the one being measured in the screentime. also what happens if theres 4 windows directly at your screen does it measure all of them at once??

**Comment by Rahsna** [comment]
Hi :) I am not the author, but it seems they have not updated the project since 2022, judging on the #latest tag, so I will try and answer your question instead 🙂

It only measures one app at a time. The one Window that has focus.

It asks Windows which app currently has focus and measures the time based off of that information.

I hope that was the info you were looking for 🙂

**Comment by Furshia** [comment]
Thank you good fellow ❤️
